# Chapter 2 - A First Example

In [55]:
# Imports
from tensorflow.keras.datasets import mnist
from tensorflow import keras
from tensorflow.keras import layers

# Load data
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

In [56]:
# Look at training data
display(train_images.shape)

display(len(train_labels))

display(train_labels)

(60000, 28, 28)

60000

array([5, 0, 4, ..., 5, 6, 8], shape=(60000,), dtype=uint8)

In [57]:
# Look at test data
display(test_images.shape)

display(len(test_labels))

display(test_labels)

(10000, 28, 28)

10000

array([7, 2, 1, ..., 4, 5, 6], shape=(10000,), dtype=uint8)

In [58]:
# Create a model
model = keras.Sequential([
    layers.Dense(512, activation='relu', input_shape=(28*28,)),
    layers.Dense(10, activation='softmax')
])

display(model)

/home/jonathan/Projects/deep_learning_with_python/.venv/lib/python3.10/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


<Sequential name=sequential_5, built=True>

In [59]:
# Compile the model
model.compile(optimizer='rmsprop',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

display(model)

<Sequential name=sequential_5, built=True>

In [60]:
# Reshape the image data for modeling
train_images = train_images.reshape((60_000, 28*28))
train_images = train_images.astype("float32")/255
test_images = test_images.reshape((10_000, 28*28))
test_images = test_images.astype("float32")/255

display(train_images.shape)
display(test_images.shape)


(60000, 784)

(10000, 784)

In [61]:
# Fit the model

model.fit(train_images, train_labels, epochs=5, batch_size=128)

Epoch 1/5
469/469 ━━━━━━━━━━━━━━━━━━━━ 6s 11ms/step - accuracy: 0.8777 - loss: 0.4273
Epoch 2/5
469/469 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.9664 - loss: 0.1168
Epoch 3/5
469/469 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.9796 - loss: 0.0693
Epoch 4/5
469/469 ━━━━━━━━━━━━━━━━━━━━ 6s 12ms/step - accuracy: 0.9857 - loss: 0.0502
Epoch 5/5
469/469 ━━━━━━━━━━━━━━━━━━━━ 6s 12ms/step - accuracy: 0.9889 - loss: 0.0380


In [62]:
# Make predictions
test_digits = test_images[0:10]
predictions = model.predict(test_digits)
display(predictions[0])
display(predictions[0].argmax())
display(predictions[0][1])
test_labels[0]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step


array([2.4883892e-07, 6.9893766e-09, 5.9168473e-05, 6.7409484e-05,
       3.6960786e-12, 1.1957792e-07, 1.1984002e-11, 9.9985981e-01,
       9.3695007e-08, 1.3200848e-05], dtype=float32)

np.int64(7)

np.float32(6.9893766e-09)

np.uint8(7)

In [63]:
# Evaluate the Model
test_loss, test_acc = model.evaluate(test_images, test_labels)
print(f"test_acc: {test_acc}")

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9742 - loss: 0.0797
test_acc: 0.977400004863739
